{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "wosa.fullname" . }}
  namespace: {{ include "wosa.namespace" . }}
  labels:
    {{- include "wosa.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout | quote }}
    {{- with .Values.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "wosa.nginx.name" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
